In [23]:
from topsis import topsis
import numpy as np
import math 
data = []
baris = 0
kolom = 6
bobot = []
I = []

In [24]:
def deklarasi_ukuranData():
    global data
    global baris
    global kolom
    #deklarasi matrix sementara
    baris = int(input("Masukkan Jumlah Baris Data : "))
    data = np.zeros((baris, kolom), dtype=float)
    print("Data Sementara : ")
    print(data)
    print("Ukuran Data : ", data.shape)

In [25]:
def input_data():
    global data
    global baris
    global kolom
    #input data ke matrix
    for x in range(baris):
        print("Input Data Alternatif ke-", x, " :")
        for y in range(kolom):
            if y == 0:
                print("Masukkan Nilai C1")
                a = float(input())
                data[x][y] = a
            elif y == 1:
                print("Masukkan Nilai C2")
                a = float(input())
                data[x][y] = a
            elif y == 2:
                print("Masukkan Nilai C3")
                a = float(input())
                data[x][y] = a
            elif y == 3:
                print("Masukkan Nilai C4")
                a = float(input())
                data[x][y] = a
            elif y == 4:
                print("Masukkan Nilai C5")
                a = float(input())
                data[x][y] = a
            elif y == 5:
                print("Masukkan Nilai C6")
                a = float(input())
                data[x][y] = a

In [26]:
#Tahapan Normalisasi
def normalisasi_data():
    for y in range(kolom):
        jumlah = 0
        for x in range(baris):
            jumlah = jumlah + pow(data[x][y],2)
        jumlah = math.sqrt(jumlah)
        print(jumlah)
        for x in range(baris):
            data[x][y] = data[x][y]/jumlah
    print("Data Setelah Ternormalisasi : ")
    print(data)

In [27]:
def input_bobot():
    global bobot
    global kolom
    bobot = np.zeros(kolom)
    print("Input Bobot Kriteria")
    for y in range(kolom):
        print("Masukan Nilai Bobot Kriteria C",y+1)
        a = float(input())
        bobot[y] = a
    print("Nilai Bobot Penilaian :")
    print(bobot)

In [28]:
def jenis_kriteria():
    global I
    I = np.zeros(kolom)
    print("Input Jenis Kriteria")
    print("1 = Benefit & 0 = Cost")
    for y in range(kolom):
        print("Masukan Nilai Jenis Kriteria C",y+1)
        a = float(input())
        I[y] = a

In [29]:
def kriteria():
    global I
    global bobot
    for y in range(kolom):
        print("Kriteria C", y+1)
        print("Bobot : ", bobot[y])
        if I[y] == 1:
            print("Jenis : Benefit")
        else:
            print("Jenis : Cost")

In [30]:
def ranking():
    global data
    global bobot
    global I
    decision = topsis(data, bobot, I)
    print(decision)

In [31]:
def menu():
    print("\nPilih Operasi : ")
    print("1. Deklarasi Banyak Data")
    print("2. Input Data")
    print("3. Kosongkan Data")
    print("4. Lihat Data")
    print("5. Normalisasi Data")
    print("6. Input Bobot Kriteria")
    print("7. Input Jenis Kriteria")
    print("8. Lihat Bobot dan Jenis Kriteria")
    print("9. Perangkingan dengan TOPSIS")

In [32]:
def main():
    menu()
    global data
    pilihan = int(input("Masukkan Pilihan Operasi : "))
    if pilihan == 1:
        deklarasi_ukuranData()
        main()
    elif pilihan == 2:
        input_data()
        main()
    elif pilihan == 3:
        data = np.zeros((2, 2))
        main()
    elif pilihan == 4:
        print("Data Saat Ini : ")
        print(data)
        main()
    elif pilihan == 5:
        normalisasi_data()
        main()
    elif pilihan == 6:
        input_bobot()
        main()
    elif pilihan == 7:
        jenis_kriteria()
        main()
    elif pilihan == 8:
        kriteria()
        main()
    elif pilihan == 9:
        ranking()
        main()
    else :
        print("Pilihan Tidak Tersedia")

In [33]:
main()


Pilih Operasi : 
1. Deklarasi Banyak Data
2. Input Data
3. Kosongkan Data
4. Lihat Data
5. Normalisasi Data
6. Input Bobot Kriteria
7. Input Jenis Kriteria
8. Lihat Bobot dan Jenis Kriteria
9. Perangkingan dengan TOPSIS
Masukkan Pilihan Operasi : 1
Masukkan Jumlah Baris Data : 6
Data Sementara : 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Ukuran Data :  (6, 6)

Pilih Operasi : 
1. Deklarasi Banyak Data
2. Input Data
3. Kosongkan Data
4. Lihat Data
5. Normalisasi Data
6. Input Bobot Kriteria
7. Input Jenis Kriteria
8. Lihat Bobot dan Jenis Kriteria
9. Perangkingan dengan TOPSIS
Masukkan Pilihan Operasi : 2
Input Data Alternatif ke- 0  :
Masukkan Nilai C1
2
Masukkan Nilai C2
3
Masukkan Nilai C3
3
Masukkan Nilai C4
4
Masukkan Nilai C5
5
Masukkan Nilai C6
5
Input Data Alternatif ke- 1  :
Masukkan Nilai C1
3
Masukkan Nilai C2
5
Masukkan Nilai C3
4
Masukkan Nilai C4
4
Masukkan Nilai C5
5
Masukkan Nilai C6
4


In [ ]:
data

In [ ]:
bobot

In [ ]:
decision = topsis(data, bobot, I)

In [ ]:
decision

In [ ]:
ranking()